version: '3'

services:
  devcontainer:
    container_name: ai-dashboard.devcontainer
    build:
      context: .
      dockerfile: ./local/devcontainer/Dockerfile
    working_dir: /workspace
    command: make app
    ports:
      - "${API_PORT}:${API_PORT}"
      - "${WEB_PORT}:${WEB_PORT}"
    volumes:
      - .:/workspace
